title: ToradorAPI Docs
email: hello@crugg.de
description: The official Documentation of the ToradorAPI Project.
baseurl: "/docs"
url: "https://toradorapi.github.io"
search: false
plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
mdl_colors: orange-amber
copyright: The ToradorAPI Project, CRUGG
search: true
menu_style: dropdown
